name: Ruby

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Generate a custom feed
      run: bundle exec exe/generate_feed.rb kentaro > feed.rss
